import { DefaultTheme } from "styled-components";

export const theme: DefaultTheme = {
  spacing: {
    xs: "4px",
    sm: "8px",
    md: "16px",
    lg: "24px",
    xl: "40px",
  },
  fontSizes: {
    sm: "0.875rem",
    md: "1rem",
    lg: "1.25rem",
    xl: "1.5rem",
  },
  fontWeights: {
    regular: 400,
    medium: 500,
    bold: 700,
  },
  colors: {
    primary: "#0070f3",
    primaryDark: "#004a99",
    primaryHover: "#007bff",
    secondary: "#ff4081",
    text: "#333",
    textLight: "#eee",
    textPrimary: "#212121",
    textSecondary: "#757575",
    textBody: "#4f4f4f",
    border: "#ddd",
    background: "#fff",
    backgroundLight: "#ffffff",
    footerBackground: "#222",
    accentBackground: "#f5f5f5",
    success: "#28a745",
    successDark: "#1e7e34",
    danger: "#dc3545",
    dangerDark: "#a71d2a",
    dangerHover: "#c82333",

    buttonDefault: "#f0f2f5",
    buttonDefaultHover: "#e6e8eb",
    borderColor: "#d9d9d9",
    borderColorHover: "#4096ff",
    disabledBackground: "#f5f5f5",
    disabledText: "rgba(0, 0, 0, 0.25)",
    disabledBorder: "#d9d9d9",
  },
  borderRadius: {
    sm: "4px",
    md: "8px",
    lg: "12px",
  },
};
